### PR TITLE
Add RSS feed for changelog

### PR DESCRIPTION
**Pull request by 40thieves**
Adds a fairly minimal RSS feed for the changelog, as originally discussed in [this forum thread](https://discuss.codemirror.net/t/possible-to-get-an-rss-feed-for-the-changelog/3694) (finally found the time to finish this up!)

I needed to make a few changes to the existing code, but tried to keep them as minimal as possible. Happy to make any changes as you see fit.

For the XML structure of the feed, I am not an RSS expert so I mostly tried to follow the Github releases Atom feed (e.g. [the CM5 one](https://github.com/codemirror/CodeMirror/releases.atom)). Unfortunately I couldn't seem to find a good Atom feed validator to double check it. Again happy to make changes here.

An unknown is what you use for serving the site, and whether it will set `Content-Type` appropriately. For my testing, I used [serve](https://www.npmjs.com/package/serve) which seems to pick it up automatically from the extension. But this might require some additional config.

### CODE REVIEW

**Comment by marijnh** [comment]
Nice, thanks! Should we not also add a tag to the HTML changelog page that references this URL? How do people discover feeds nowadays?

**Comment by 40thieves** [comment]
> Should we not also add a tag to the HTML changelog page that references this URL?

Good point 🙂 

> How do people discover feeds nowadays?

It appears that you add an `<link rel="alternate">`: https://www.petefreitag.com/item/384.cfm I'll look into that now.

**Comment by 40thieves** [comment]
Now done. I used a bit of a hacky approach to inserting `<link>`s into the template in https://github.com/codemirror/website/pull/26/commits/2f27815821258d340902f3ea4ece9fc705eec1c4. If you have better ideas i'd be open to them. The actual link is added in https://github.com/codemirror/website/pull/26/commits/82a90681f24cc1c3e527fd0453e255b01b0635e7.

**Comment by marijnh** [comment]
Thanks, merged! This validator flags a bunch of validity issues though: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcodemirror.net%2F6%2Fdocs%2Fchangelog%2Ffeed.atom

**Comment by 40thieves** [comment]
Hmm ok thanks for checking, I'll see if fix those. It will probably will need to wait a bit though I'm afraid - so if you'd like to roll back until then that's fine with me.

**Comment by marijnh** [comment]
Nah, most reader software can probably deal with those, and I don't expect all that many people to discover the feed all that quickly anyway.

**Comment by 40thieves** [comment]
Indeed, it seems that Slack's `/feed` command works just fine (which was my original motivation).

**Comment by marijnh** [comment]
I've reverted this, since it broke the HTML changelog page, and I don't really care enough about this feature to review and fix this code.

**Comment by 40thieves** [comment]
Ok fair enough. Now that the number of packages is reduced, I think it's feasible to subscribe via Github releases.

**Pull request merged**
